//cria usuário
POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "lua",
    "username":"lua182"
}

###

//busca tarefas por nome de usuário
http://localhost:3333/todos 
Content-Type: application/json
username: lua182

###

//criar tarefa
POST http://localhost:3333/todos
Content-Type: application/json
username: lua182

 {
    "title": "aaaaaaa",
    "deadline":"new Date()"
}

###

# alterar tarefa por id da tarefa

PUT http://localhost:3333/todos/ab61c652-ca65-42fa-bdef-010737951
Content-Type: application/json
username: lua182

{
    "title": "tarefa ALTERADA",
    "deadline":"amanhã"
}

###

//altera status da tarefa

PATCH http://localhost:3333/todos/fe1c711e-af54-4566-bd7b-4dca77b6354f/done
Content-Type: application/json
username: lua182


###

DELETE http://localhost:3333/todos/55ce1ba8-9552-43d8-9bb4-6c94b1240ccb
Content-Type: application/json
username: mariri

